version: "3"

services:

  elasticsearch:
    image: "docker.elastic.co/elasticsearch/elasticsearch:8.8.2"
    container_name: "elasticsearch"
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "discovery.type=single-node"
      - xpack.security.enabled=false
    volumes:
      - "./logstashConfig:/config"
    expose:
      - 9200
    ports:
      - "9200:9200"
    networks:
      - elastic
  
  kibana:
    image: "docker.elastic.co/kibana/kibana:8.8.2"
    container_name: "kibana"
    depends_on:
      - elasticsearch
    expose:
      - 5601
    ports:
      - "5601:5601" 
    networks:
      - elastic
      
  
  logstash:
    image: "docker.elastic.co/logstash/logstash:8.8.2"
    volumes:
      - "./logstashConfig/logstash.yml:/usr/share/logstash/config/logstash.yml"
      - "./logstashConfig/logstash.conf:/usr/share/logstash/pipeline/logstash.conf"
    container_name: "logstash"
    depends_on:
      - elasticsearch
    expose:
      - 5044
    ports:
      - "5044:5044"
      - "5110:5110"
      - "9600:9600"
    networks:
      - elastic
      
  phase5:
    image: "dipanshusingh2107/phase5:latest"
    container_name: "phase5"
    depends_on:
      - logstash
      - kibana
      - elasticsearch
    links:
      - logstash
    
    expose:
      - 8081
    ports:
      - "8081:8081"
    networks:
      - elastic
      
networks:
  elastic:
    driver: bridge
  
  